version: 2.1
jobs:
  weave:
    docker:
    - image: magalixcorp/weave-validator:dev
    steps:
    - checkout
    - run:
        command: weave-validator --path kubernetes --policies-path policies --git-repo-token ${GITHUB_TOKEN} --remediate

workflows:
  weave:
    jobs:
    - weave:
        filters:
          branches:
            only:
            - circleci
          tags:
            only: /^v.*