apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-3
  labels:
    app: myapp-3
spec:
  selector:
    matchLabels:
      app: myapp-3
  template:
    metadata:
      labels:
        app: myapp-3
    spec:
      containers:
        - name: container-1
          image: ubuntu
          command: ["/bin/bash"]
          args:
            - "-c"
            - "sleep 1d"
          securityContext:
            privileged: true
