apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        # mglx:ignore
        - name: container-1
          securityContext:
            allowPrivilegeEscalation: true
        - name: container-2
          securityContext:
            allowPrivilegeEscalation: true
        - name: container-3
          securityContext:
            allowPrivilegeEscalation: true
---
# mglx:ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-2
  labels:
    app: myapp-2
spec:
  selector:
    matchLabels:
      app: myapp-2
  template:
    metadata:
      labels:
        app: myapp-2
    spec:
      containers:
        - name: container-1
          securityContext:
            allowPrivilegeEscalation: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-3
  labels:
    app: myapp-3
spec:
  selector:
    matchLabels:
      app: myapp-3
  template:
    metadata:
      labels:
        app: myapp-3
    spec:
      containers:
        - name: container-1
          securityContext:
            allowPrivilegeEscalation: true # mglx:ignore

