name: Magalix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, test ]

jobs:
  magalix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ github.event.pull_request.head.sha || github.sha }}
#     - name: Magalix
#       uses: magalixcorp/magalix-action@test
#       with:
#         webhook: ${{ secrets.GUARD_WEBHOOK }}
