name: Magalix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  magalix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo $GITHUB_REF - $GITHUB_HEAD_REF
    
#     - name: Magalix
#       uses: magalixcorp/magalix-action@test
#       with:
#         webhook: ${{ secrets.GUARD_WEBHOOK }}
