name: Magalix

on:
  push:
    branches: [ master, ignore ]
  pull_request:
    branches: [ master, ignore ]

jobs:
  magalix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Magalix
      uses: magalixcorp/magalix-action@test
      with:
        webhook: ${{ secrets.IAC_GUARD_URL }}
        auto-remediation: true

